import { courses as served, allCourses, universities, suppressedIds, policyExcludedCourses, testFixtureCourses } from '@/data';
import { validateCatalogue } from '@/lib/validation';
import { codeCollisions, identityRisks, unsupportedCodeProvenance, unevidencedIdentities } from '@/lib/identity-invariant';
const n=(id:string)=>universities.find(u=>u.id===id)?.name??id;
const by=(s:string)=>served.filter(c=>c.provenance.verificationStatus===s).length;
console.log('served', served.length, '| all', allCourses.length, '| suppressed', suppressedIds.size, '| policy-excluded', policyExcludedCourses.length);
console.log('verified', by('verified'), '| partial', by('partially-verified'), '| awaiting-pub', by('awaiting-publication'), '| awaiting-data', by('awaiting-data'), '| demo', by('demo'));
const v=validateCatalogue(served, universities); const sev:Record<string,number>={};
for(const i of v.issues) sev[i.severity]=(sev[i.severity]??0)+1;
console.log('validation', JSON.stringify(sev), '| duplicates', v.duplicates.length);
console.log('unevidenced', unevidencedIdentities(served).length, '| collisions', codeCollisions(served).length, '| risks', identityRisks(served).length, '| url-codes', unsupportedCodeProvenance(served).length);
const unis=new Set(served.map(c=>c.universityId));
const withData=new Set(served.filter(c=>['verified','partially-verified'].includes(c.provenance.verificationStatus)).map(c=>c.universityId));
console.log('universities', unis.size, '| with verified/partial', withData.size, '| without:', [...unis].filter(u=>!withData.has(u)).map(n).join(', ')||'none');
console.log('\npartially verified:');
for(const c of served.filter(c=>c.provenance.verificationStatus==='partially-verified')) console.log(' ', n(c.universityId), '|', c.name, c.degreeType, c.courseCode, '|', c.id);
console.log('\nKCL rows:');
for(const c of served.filter(c=>c.universityId==='kcl')) console.log(' ', c.applicationYear, c.provenance.verificationStatus.padEnd(22), (c.courseCode??'----').padEnd(6), c.name, c.degreeType);
console.log('\nQMUL rows:');
for(const c of served.filter(c=>c.universityId==='qmul')) console.log(' ', c.applicationYear, c.provenance.verificationStatus.padEnd(22), (c.courseCode??'----').padEnd(6), c.name, c.degreeType);
